### ISSUE TITLE
Input with button on same line, no widths

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-tips#174]
```css
/*
<div class="advo-input-group">
    <div>
        <input type="password" placeholder="Password">
    </div>
    <div>
        <button class="advo-button">Go</button>
    </div>
</div>
*/

.advo-input-group {
    width: 100%;
    display: table;
}
.advo-input-group > div {
    display: table-cell;
    width: 100%;
    background-clip: padding-box;
}
.advo-input-group > div + div {
    border-left: 1rem solid transparent;
}
.advo-input-group input {
    border: 0.1rem solid #0fe3ff;
    padding: 1rem;
    width: 100%;
}
.advo-input-group button {
    border: 0.1rem solid #0fe3ff;
    padding: 1rem;
    margin: 0;
    width: auto;
}
```

![](https://user-images.githubusercontent.com/218624/38176461-27720b1a-35a4-11e8-893e-c4e7959a21d7.png)
